version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          name: dotnet test
          command: dotnet test ./Dena.CodeAnalysis.Testing.sln
